// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYB6KhFFKywLxjBfu2vMId0BW2i42n6cM',
    appId: '1:761707568090:web:9a21b0f2817751357e7ee3',
    messagingSenderId: '761707568090',
    projectId: 'moviesnearby',
    authDomain: 'moviesnearby.firebaseapp.com',
    storageBucket: 'moviesnearby.appspot.com',
    measurementId: 'G-2FD8HWSWB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEd2uxX--C-YS4wgzBn5tmD84-Vpg-tDY',
    appId: '1:761707568090:android:bcd8942fa281e7d07e7ee3',
    messagingSenderId: '761707568090',
    projectId: 'moviesnearby',
    storageBucket: 'moviesnearby.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLvhcG8cgo7HMq1eUwJgnUKiFqVF8nEQ',
    appId: '1:761707568090:ios:a0bd8021fad123de7e7ee3',
    messagingSenderId: '761707568090',
    projectId: 'moviesnearby',
    storageBucket: 'moviesnearby.appspot.com',
    iosClientId: '761707568090-rpsm5oedo3heag7q82r40u3mr4ns3cof.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesnearby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLvhcG8cgo7HMq1eUwJgnUKiFqVF8nEQ',
    appId: '1:761707568090:ios:56ea9341e923da5d7e7ee3',
    messagingSenderId: '761707568090',
    projectId: 'moviesnearby',
    storageBucket: 'moviesnearby.appspot.com',
    iosClientId: '761707568090-510646tj6nn5u8u3rmqjigttirecbtrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesnearby.RunnerTests',
  );
}
